name: autoclose
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/vlastachu/autoclose

environment:
  sdk: '>=2.19.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  async: ^2.11.0
