name: autoclose
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/vlastachu/autoclose

environment:
  sdk: '>=3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  vm_service: ^11.9.0
  build_runner:
  mockito: ^5.4.0

dependencies:
  async: ^2.11.0
