name: autoclose
description: is a package designed to reduce the entire boilerplate from things that can be `.dispose()`d, `.close()`d or whatever!
version: 1.0.0
repository: https://github.com/vlastachu/autoclose
issue_tracker: https://github.com/vlastachu/autoclose/issues

environment:
  sdk: '>=3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  vm_service: ^11.9.0
  build_runner:
  mockito: ^5.4.0
  total_lints:

dependencies:
  async: ^2.11.0
  meta: ^1.11.0
