name: autoclose_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  analyzer:
  analyzer_plugin:
  custom_lint_builder: ^0.5.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  total_lints:
