name: autoclose_flutter
description: autoclose_flutter is a package providing AutoClose functionality for the Flutter platform
version: 1.0.0
repository: https://github.com/vlastachu/autoclose
issue_tracker: https://github.com/vlastachu/autoclose/issues

environment:
  sdk: '^3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  autoclose:

dependency_overrides:
  autoclose:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  vm_service: ^11.9.0
  mockito: ^5.4.0

flutter:
